definitions:
  app.Paper:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  errcode.Error:
    type: object
  model.Article:
    properties:
      content:
        description: 文章内容
        type: string
      coverImageUrl:
        description: 封面图片地址
        type: string
      createdBy:
        description: 创建人
        type: string
      createdOn:
        description: 创建时间  todo uint32 可能不太够用
        type: integer
      deletedOn:
        description: 删除时间
        type: integer
      desc:
        description: 文章简述
        type: string
      id:
        type: integer
      isDeleted:
        description: 是否删除 0 未删除 1 已删除
        type: integer
      modifiedBy:
        description: 修改人
        type: string
      modifiedOn:
        description: 修改时间
        type: integer
      state:
        description: 状态 0 启用， 1 禁用
        type: integer
      title:
        description: 文章标题
        type: string
    type: object
  model.ArticleSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Article'
        type: array
      paper:
        $ref: '#/definitions/app.Paper'
    type: object
  model.Tag:
    properties:
      createdBy:
        description: 创建人
        type: string
      createdOn:
        description: 创建时间  todo uint32 可能不太够用
        type: integer
      deletedOn:
        description: 删除时间
        type: integer
      id:
        type: integer
      isDeleted:
        description: 是否删除 0 未删除 1 已删除
        type: integer
      modifiedBy:
        description: 修改人
        type: string
      modifiedOn:
        description: 修改时间
        type: integer
      name:
        description: 标签名
        type: string
      state:
        description: 状态 0 启用， 1 禁用
        type: integer
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      paper:
        $ref: '#/definitions/app.Paper'
    type: object
info:
  contact: {}
  description: Go 语言编程之旅：一起用 Go 做项目 第二章
  title: 博客系统
  version: "1.0"
paths:
  /api/v1/articles:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.ArticleSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个文章
    post:
      parameters:
      - description: 文章名
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 文章内容
        in: body
        name: content
        required: true
        schema:
          type: string
      - description: 状态
        in: body
        name: state
        schema:
          type: integer
      - description: 创建者
        in: body
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.ArticleSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增文章
  /api/v1/articles/{id}:
    delete:
      parameters:
      - description: 文章id
        in: body
        name: id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.ArticleSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 删除文章
    put:
      parameters:
      - description: 文章id
        in: body
        name: id
        required: true
        schema:
          type: integer
      - description: 文章名
        in: body
        name: name
        schema:
          type: string
      - description: 文章内容
        in: body
        name: content
        schema:
          type: string
      - description: 状态
        in: body
        name: state
        schema:
          type: integer
      - description: 修改者
        in: body
        name: modified_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.ArticleSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新文章
  /api/v1/tags:
    get:
      parameters:
      - description: 标签名
        in: query
        name: name
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个标签
    post:
      parameters:
      - description: 标签名
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 状态
        in: body
        name: state
        schema:
          type: integer
      - description: 创建者
        in: body
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增标签
    put:
      parameters:
      - description: 标签 id
        in: path
        name: id
        required: true
        type: integer
      - description: 标签名
        in: body
        name: name
        schema:
          type: string
      - description: 状态
        in: body
        name: state
        schema:
          type: integer
      - description: 修改者
        in: body
        name: modified_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新标签
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: 签名 id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 删除标签
  /upload/file:
    post:
      parameters:
      - description: 上传文件
        in: formData
        name: file
        required: true
        type: file
      - description: 文件类型
        in: formData
        name: type
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 文件上传
swagger: "2.0"
